**Payments**

In [11]:
import numpy as np
import pandas as pd
from pathlib import Path

In [12]:
file_path = Path.cwd().parent.parent/"Data"/"Cleaned"/"Payments.csv"
df = pd.read_csv(file_path)
df

     Payment_ID Project_ID Payment_Date  Amount_Cr  Payment_Status
0      PAY20001      P1001   2026-06-11      13.69        Approved
1      PAY20002      P1001   2026-05-16      12.04        Approved
2      PAY20003      P1001          NaN       6.97            Paid
3      PAY20004      P1001   2026-05-15       6.81  Partially Paid
4      PAY20005      P1001   2026-07-16       1.43         On Hold
...         ...        ...          ...        ...             ...
1628   PAY21629      P1057   2026-07-29       3.86             NaN
1629   PAY21630      P1167   2023-08-04      14.26         Pending
1630   PAY21631      P1204   2023-05-30       8.61        Approved
1631   PAY21632      P1210   2023-11-25       7.57         Pending
1632   PAY21633      P1146   2023-02-10      12.10  Partially Paid

[1633 rows x 5 columns]

In [13]:
df["Payment_Date"] = pd.to_datetime(df["Payment_Date"])
df["Payment_Year"] = (df["Payment_Date"].dt.year)
df["Payment_Month"] = (df["Payment_Date"].dt.month)

In [14]:
df

,Payment_ID,Project_ID,Payment_Date,Amount_Cr,Payment_Status,Payment_Year,Payment_Month
0,PAY20001,P1001,2026-06-11,13.69,Approved,2026.0,6.0
1,PAY20002,P1001,2026-05-16,12.04,Approved,2026.0,5.0
2,PAY20003,P1001,NaT,6.97,Paid,NaN,NaN
3,PAY20004,P1001,2026-05-15,6.81,Partially Paid,2026.0,5.0
4,PAY20005,P1001,2026-07-16,1.43,On Hold,2026.0,7.0
...,...,...,...,...,...,...,...
1628,PAY21629,P1057,2026-07-29,3.86,NaN,2026.0,7.0
1629,PAY21630,P1167,2023-08-04,14.26,Pending,2023.0,8.0
1630,PAY21631,P1204,2023-05-30,8.61,Approved,2023.0,5.0
1631,PAY21632,P1210,2023-11-25,7.57,Pending,2023.0,11.0
1632,PAY21633,P1146,2023-02-10,12.10,Partially Paid,2023.0,2.0

In [15]:
df.to_csv("../../Data/Processed/Payments.csv", index=False)